// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import { combineImportEntries, defaultImportEntries } from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { useEffect, useState, useCallback, useMemo, useRef } from 'react';
import React from 'react';
import dynamic from 'next/dynamic';
import { getVideoProvider } from 'src/core/molecules/VideoPlayer/VideoProvider';
import { useTheme } from 'src/core/context/ThemeContext';
import { Sun, Moon, X, Menu, ChevronLeft, ChevronDown, Globe } from 'lucide-react';
import { FacebookShareButton, TwitterShareButton, LinkedinShareButton, PinterestShareButton, EmailShareButton } from 'react-share';
import { SitecoreImage } from 'src/core/atom/Images';
import { SitecoreLink } from 'src/core/atom/Link';
import { useRouter } from 'next/router';
import SearchInputWidget from 'src/core/molecules/SearchInput';
import PlaceholderBanner from 'src/core/molecules/PageTitleBanner/PlaceholderBanner';
import { useSitecore, Placeholder, Text, withDatasourceCheck, RichText, DateField, CdpHelper } from '@sitecore-content-sdk/nextjs';
import { DefaultBanner } from 'src/core/molecules/NotificationBanner/DefaultBanner';
import { ErrorBanner } from 'src/core/molecules/NotificationBanner/ErrorBanner';
import { Tabs, TabsList, TabsTrigger, TabsContent } from 'src/core/ui/tabs';
import { Button } from 'src/core/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogClose } from 'src/core/ui/dialog';
import { cn } from 'src/core/lib/utils';
import { NavigationMenu, NavigationMenuItem, NavigationMenuList, NavigationMenuTrigger } from 'src/core/ui/navigation-menu';
import { Sheet, SheetContent, SheetTrigger } from 'src/core/ui/sheet';
import { Card } from 'src/core/ui/card';
import Link from 'next/link';
import DropdownMenu from 'src/core/molecules/LanguageSelector/DropdownMenu';
import DropdownButton from 'src/core/atom/DropdownButton';
import LanguageFlagIcon from 'src/core/atom/LanguageFlagIcon';
import { NavigationList } from 'src/core/molecules/NavigationItem/NavigationList';
import HeaderNavigation from 'src/core/molecules/NavigationItem/HeaderNavigation';
import CustomButton from 'src/core/molecules/CTAButton/CustomButton';
import CardItem from 'src/core/molecules/ContentCard/CardItem';
import { getBlogCustomRoute } from 'src/lib/utils/blog-url-helper';
import Slider from 'react-slick';
import SlickArrowButton from 'src/core/atom/SlickArrowButton';
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from 'src/core/ui/breadcrumb';
import { AccordionContent, AccordionItem, AccordionTrigger, Accordion } from 'src/core/ui/accordion';
import client from 'lib/sitecore-client';
import Image from 'next/image';
import * as FEAAS from '@sitecore-feaas/clientside/react';
import nextConfig from 'next.config';
import { pageView } from '@sitecore-cloudsdk/events/browser';
import config from 'sitecore.config';

const importMap = [
  {
    module: 'react',
    exports: [
      { name: 'useEffect', value: useEffect },
      { name: 'useState', value: useState },
      { name: 'useCallback', value: useCallback },
      { name: 'useMemo', value: useMemo },
      { name: 'useRef', value: useRef },
      { name: 'default', value: React },
    ]
  },
  {
    module: 'next/dynamic',
    exports: [
      { name: 'default', value: dynamic },
    ]
  },
  {
    module: 'src/core/molecules/VideoPlayer/VideoProvider',
    exports: [
      { name: 'getVideoProvider', value: getVideoProvider },
    ]
  },
  {
    module: 'src/core/context/ThemeContext',
    exports: [
      { name: 'useTheme', value: useTheme },
    ]
  },
  {
    module: 'lucide-react',
    exports: [
      { name: 'Sun', value: Sun },
      { name: 'Moon', value: Moon },
      { name: 'X', value: X },
      { name: 'Menu', value: Menu },
      { name: 'ChevronLeft', value: ChevronLeft },
      { name: 'ChevronDown', value: ChevronDown },
      { name: 'Globe', value: Globe },
    ]
  },
  {
    module: 'react-share',
    exports: [
      { name: 'FacebookShareButton', value: FacebookShareButton },
      { name: 'TwitterShareButton', value: TwitterShareButton },
      { name: 'LinkedinShareButton', value: LinkedinShareButton },
      { name: 'PinterestShareButton', value: PinterestShareButton },
      { name: 'EmailShareButton', value: EmailShareButton },
    ]
  },
  {
    module: 'src/core/atom/Images',
    exports: [
      { name: 'SitecoreImage', value: SitecoreImage },
    ]
  },
  {
    module: 'src/core/atom/Link',
    exports: [
      { name: 'SitecoreLink', value: SitecoreLink },
    ]
  },
  {
    module: 'next/router',
    exports: [
      { name: 'useRouter', value: useRouter },
    ]
  },
  {
    module: 'src/core/molecules/SearchInput',
    exports: [
      { name: 'default', value: SearchInputWidget },
    ]
  },
  {
    module: 'src/core/molecules/PageTitleBanner/PlaceholderBanner',
    exports: [
      { name: 'default', value: PlaceholderBanner },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'useSitecore', value: useSitecore },
      { name: 'Placeholder', value: Placeholder },
      { name: 'Text', value: Text },
      { name: 'withDatasourceCheck', value: withDatasourceCheck },
      { name: 'RichText', value: RichText },
      { name: 'DateField', value: DateField },
      { name: 'CdpHelper', value: CdpHelper },
    ]
  },
  {
    module: 'src/core/molecules/NotificationBanner/DefaultBanner',
    exports: [
      { name: 'DefaultBanner', value: DefaultBanner },
    ]
  },
  {
    module: 'src/core/molecules/NotificationBanner/ErrorBanner',
    exports: [
      { name: 'ErrorBanner', value: ErrorBanner },
    ]
  },
  {
    module: 'src/core/ui/tabs',
    exports: [
      { name: 'Tabs', value: Tabs },
      { name: 'TabsList', value: TabsList },
      { name: 'TabsTrigger', value: TabsTrigger },
      { name: 'TabsContent', value: TabsContent },
    ]
  },
  {
    module: 'src/core/ui/button',
    exports: [
      { name: 'Button', value: Button },
    ]
  },
  {
    module: 'src/core/ui/dialog',
    exports: [
      { name: 'Dialog', value: Dialog },
      { name: 'DialogContent', value: DialogContent },
      { name: 'DialogHeader', value: DialogHeader },
      { name: 'DialogTitle', value: DialogTitle },
      { name: 'DialogClose', value: DialogClose },
    ]
  },
  {
    module: 'src/core/lib/utils',
    exports: [
      { name: 'cn', value: cn },
    ]
  },
  {
    module: 'src/core/ui/navigation-menu',
    exports: [
      { name: 'NavigationMenu', value: NavigationMenu },
      { name: 'NavigationMenuItem', value: NavigationMenuItem },
      { name: 'NavigationMenuList', value: NavigationMenuList },
      { name: 'NavigationMenuTrigger', value: NavigationMenuTrigger },
    ]
  },
  {
    module: 'src/core/ui/sheet',
    exports: [
      { name: 'Sheet', value: Sheet },
      { name: 'SheetContent', value: SheetContent },
      { name: 'SheetTrigger', value: SheetTrigger },
    ]
  },
  {
    module: 'src/core/ui/card',
    exports: [
      { name: 'Card', value: Card },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: Link },
    ]
  },
  {
    module: 'src/core/molecules/LanguageSelector/DropdownMenu',
    exports: [
      { name: 'default', value: DropdownMenu },
    ]
  },
  {
    module: 'src/core/atom/DropdownButton',
    exports: [
      { name: 'default', value: DropdownButton },
    ]
  },
  {
    module: 'src/core/atom/LanguageFlagIcon',
    exports: [
      { name: 'default', value: LanguageFlagIcon },
    ]
  },
  {
    module: 'src/core/molecules/NavigationItem/NavigationList',
    exports: [
      { name: 'NavigationList', value: NavigationList },
    ]
  },
  {
    module: 'src/core/molecules/NavigationItem/HeaderNavigation',
    exports: [
      { name: 'default', value: HeaderNavigation },
    ]
  },
  {
    module: 'src/core/molecules/CTAButton/CustomButton',
    exports: [
      { name: 'default', value: CustomButton },
    ]
  },
  {
    module: 'src/core/molecules/ContentCard/CardItem',
    exports: [
      { name: 'default', value: CardItem },
    ]
  },
  {
    module: 'src/lib/utils/blog-url-helper',
    exports: [
      { name: 'getBlogCustomRoute', value: getBlogCustomRoute },
    ]
  },
  {
    module: 'react-slick',
    exports: [
      { name: 'default', value: Slider },
    ]
  },
  {
    module: 'src/core/atom/SlickArrowButton',
    exports: [
      { name: 'default', value: SlickArrowButton },
    ]
  },
  {
    module: 'src/core/ui/breadcrumb',
    exports: [
      { name: 'Breadcrumb', value: Breadcrumb },
      { name: 'BreadcrumbItem', value: BreadcrumbItem },
      { name: 'BreadcrumbLink', value: BreadcrumbLink },
      { name: 'BreadcrumbList', value: BreadcrumbList },
      { name: 'BreadcrumbPage', value: BreadcrumbPage },
      { name: 'BreadcrumbSeparator', value: BreadcrumbSeparator },
    ]
  },
  {
    module: 'src/core/ui/accordion',
    exports: [
      { name: 'AccordionContent', value: AccordionContent },
      { name: 'AccordionItem', value: AccordionItem },
      { name: 'AccordionTrigger', value: AccordionTrigger },
      { name: 'Accordion', value: Accordion },
    ]
  },
  {
    module: 'lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image },
    ]
  },
  {
    module: '@sitecore-feaas/clientside/react',
    exports: [
      { name: '*', value: FEAAS },
    ]
  },
  {
    module: 'next.config',
    exports: [
      { name: 'default', value: nextConfig },
    ]
  },
  {
    module: '@sitecore-cloudsdk/events/browser',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  }
];

export default combineImportEntries(defaultImportEntries, importMap);
