/** @type {import('tailwindcss').Config} */
const config = {
  darkMode: ['class'],
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './stories/**/*.{js,ts,jsx,tsx}',
    './.storybook/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      zIndex: {
        '5': '5',
        '100': '100',
      },
      fontFamily: {
        satoshi: ['var(--font-satoshi)', 'sans-serif'],
        Zodiak: ['var(--font-zodiak)', 'sans-serif'],
      },
      fontSize: {
        h1: 'var(--text-5xl)',
        h2: 'var(--text-4xl)',
        h3: 'var(--text-2xl)',
        h4: 'var(--text-xl)',
        p: 'var(--text-base)',
      },
      height: {
        '41': 'var(--height-41)',
        '137': 'var(--height-137)',
        '387': 'var(--height-387)',
        '600': 'var(--height-600)',
      },
      width: {
        '600': 'var(--width-600)',
      },
      borderRadius: {
        default: 'var(--rounded)',
        sm: 'var(--rounded-sm)',
        md: 'var(--rounded-md)',
        lg: 'var(--rounded-lg)',
        xl: 'var(--rounded-xl)',
        full: 'var(--rounded-full)',
      },
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        slate: 'var(--slate)',
        'sidebar-foreground': 'var(--sidebar-foreground)',
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
        popover: {
          DEFAULT: 'var(--popover)',
          foreground: 'var(--popover-foreground)',
        },
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
        },
        tertiary: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
        },
        quaternary: {
          DEFAULT: 'var(--quaternary)',
          foreground: 'var(--quaternary-foreground)',
        },
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
        },
        destructive: {
          DEFAULT: 'var(--destructive)',
          foreground: 'var(--destructive-foreground)',
        },
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        chart: {
          '1': 'var(--chart-1)',
          '2': 'var(--chart-2)',
          '3': 'var(--chart-3)',
          '4': 'var(--chart-4)',
          '5': 'var(--chart-5)',
        },
      },
      spacing: {
        '0': 'var(--spacing-0)',
        default: 'var(--spacing-md)',
        sm: 'var(--spacing-sm)',
        md: 'var(--spacing-md)',
        lg: 'var(--spacing-lg)',
        xl: 'var(--spacing-xl)',
      },
      boxShadow: {
        sm: 'var(--shadow-light)',
        md: 'var(--shadow-medium)',
        lg: 'var(--shadow-heavy)',
      },
      keyframes: {
        'accordion-down': {
          from: {
            height: '0',
          },
          to: {
            height: 'var(--radix-accordion-content-height)',
          },
        },
        'accordion-up': {
          from: {
            height: 'var(--radix-accordion-content-height)',
          },
          to: {
            height: '0',
          },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  safelist: [
    'top-low-space',
    'top-no-space',
    'top-medium-space',
    'top-large-space',
    'bottom-low-space',
    'bottom-no-space',
    'bottom-medium-space',
    'bottom-large-space',
    'text-h1',
    'text-h2',
    'text-h3',
    'text-h4',
    'text-h5',
    'text-h6',
    'text-p',
    'text-primary',
    'text-secondary',
    'bg-primary',
    'bg-secondary',
    'bg-tertiary',
    'bg-quaternary',
    'basis-1/12',
    'basis-1/6',
    'basis-1/4',
    'basis-1/3',
    'basis-5/12',
    'basis-1/2',
    'basis-7/12',
    'basis-2/3',
    'basis-3/4',
    'basis-5/6',
    'basis-11/12',
    'basis-full',
    'md:basis-auto',
    'basis-0 grow',
    'sm:basis-1/12',
    'sm:basis-1/6',
    'sm:basis-1/4',
    'sm:basis-1/3',
    'sm:basis-5/12',
    'sm:basis-1/2',
    'sm:basis-7/12',
    'sm:basis-2/3',
    'sm:basis-3/4',
    'sm:basis-5/6',
    'sm:basis-11/12',
    'sm:basis-full',
    'sm:basis-auto',
    'sm:basis-0 sm:grow',
    'md:basis-1/12',
    'md:basis-1/6',
    'md:basis-1/4',
    'md:basis-1/3',
    'md:basis-5/12',
    'md:basis-1/2',
    'md:basis-7/12',
    'md:basis-2/3',
    'md:basis-3/4',
    'md:basis-5/6',
    'md:basis-11/12',
    'md:basis-full',
    'md:basis-auto',
    'md:basis-0 md:grow',
    'lg:basis-1/12',
    'lg:basis-1/6',
    'lg:basis-1/4',
    'lg:basis-1/3',
    'lg:basis-5/12',
    'lg:basis-1/2',
    'lg:basis-7/12',
    'lg:basis-2/3',
    'lg:basis-3/4',
    'lg:basis-5/6',
    'lg:basis-11/12',
    'lg:basis-full',
    'lg:basis-auto',
    'lg:basis-0 lg:grow',
    'xl:basis-1/12',
    'xl:basis-1/6',
    'xl:basis-1/4',
    'xl:basis-1/3',
    'xl:basis-5/12',
    'xl:basis-1/2',
    'xl:basis-7/12',
    'xl:basis-2/3',
    'xl:basis-3/4',
    'xl:basis-5/6',
    'xl:basis-11/12',
    'xl:basis-full',
    'xl:basis-auto',
    'xl:basis-0 xl:grow',
    '2xl:basis-1/12',
    '2xl:basis-1/6',
    '2xl:basis-1/4',
    '2xl:basis-1/3',
    '2xl:basis-5/12',
    '2xl:basis-1/2',
    '2xl:basis-7/12',
    '2xl:basis-2/3',
    '2xl:basis-3/4',
    '2xl:basis-5/6',
    '2xl:basis-11/12',
    '2xl:basis-full',
    '2xl:basis-auto',
    '2xl:basis-0 2xl:grow',
    'order-first',
    'order-last',
  ],
};

export default config;
