// This component was generated by @sitecore-search/cli on Fri Oct 24 2025 13:40:27 GMT+0530 (India Standard Time)

import type { ActionProp, ItemClickedAction } from '@sitecore-search/react';
import { ArticleCard } from '@sitecore-search/ui';
import { CustomButtonLink } from './CustomButtonLink';
import { ArrowRight } from 'lucide-react';

type Article = {
  id: string;
  name?: string;
  title?: string;
  url?: string;
  source_id?: string;
  image_url?: string;
  author?: string;
  description?: string;
  category?: string;
};

type ArticleCardItemCardProps = {
  className?: string;
  displayText?: boolean;
  article: Article;
  onItemClick: ActionProp<ItemClickedAction>;
  index: number;
};
const DEFAULT_IMG_URL = 'https://placehold.co/500x300?text=No%20Image';

const ArticleHorizontalItemCard = ({
  className = '',
  article,
  onItemClick,
  index,
  displayText = true,
}: ArticleCardItemCardProps) => {
  return (
    <ArticleCard.Root
      key={article.id}
      className={`group flex flex-row gap-6 p-6 my-4 w-full relative bg-white border border-[#d4d4d8] dark:border-gray-600 rounded-lg hover:shadow-lg hover:opacity-80 hover:!scale-100 transition-all duration-300 ease-linear focus-within:opacity-80 focus-within:!scale-100 focus-within:shadow-lg ${className}`}
    >
      {/* Image Section - Fixed width */}
      <div className="w-[314px] flex-none overflow-hidden rounded-md bg-gray-200">
        <ArticleCard.Image
          src={article?.image_url || DEFAULT_IMG_URL}
          className="h-full w-full object-cover object-center hover:!scale-100"
        />
      </div>

      {/* Content Section */}
      <div className="flex-1 flex flex-col gap-4 min-w-0">
        {/* Header Section */}
        <div className="flex flex-col gap-1.5 min-h-[114px]">
          {/* Category */}
          {article.category && (
            <p className="text-sm font-['Satoshi'] font-medium text-[#18181b] leading-5">
              {article.category}
            </p>
          )}

          {/* Title */}
          <ArticleCard.Title className="text-2xl font-['Zodiak'] font-bold text-[#09090b] leading-none tracking-[-0.4px]">
            {article.name || article.title}
          </ArticleCard.Title>

          {/* Description */}
          {article.description && displayText && (
            <p className="text-base font-['Satoshi'] text-[#71717a] leading-6 line-clamp-3">
              {article.description}
            </p>
          )}
        </div>

        {/* Footer Section - Button */}
        <div className="flex items-start gap-2.5">
          <CustomButtonLink
            variant="outline"
            size="default"
            field={{
              value: {
                href: article.url || '#',
                text: 'Read the Article',
                title: article.name || article.title,
              },
            }}
            onClick={(event) => {
              event.preventDefault();
              onItemClick({
                id: article.id,
                index,
                sourceId: article.source_id,
              });
            }}
            className="bg-white border-[#e4e4e7] rounded-md px-3 py-2 h-9"
          >
            {'Read the Article'}
            <ArrowRight className="w-4 h-4" aria-hidden="true" />
          </CustomButtonLink>
        </div>
      </div>
    </ArticleCard.Root>
  );
};
export default ArticleHorizontalItemCard;
