// This component was generated by @sitecore-search/cli on Wed Oct 22 2025 21:14:56 GMT+0530 (India Standard Time)

import React from 'react';
import { CardViewSwitcher } from '@sitecore-search/ui';

type CardViewSwitcherProps = {
  onToggle?: (value: string) => void;
  defaultCardView?: 'list' | 'grid';
  // Alternative prop names for compatibility
  onChange?: (mode: 'list' | 'grid') => void;
  value?: 'list' | 'grid';
};

// Grid Icon Component (2x2 grid layout)
const GridIcon = ({ className }: { className?: string }) => (
  <svg
    width="20"
    height="20"
    viewBox="0 0 20 20"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    className={className}
  >
    <path
      d="M7 1H2C1.44772 1 1 1.44772 1 2V7C1 7.55228 1.44772 8 2 8H7C7.55228 8 8 7.55228 8 7V2C8 1.44772 7.55228 1 7 1Z"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M18 1H13C12.4477 1 12 1.44772 12 2V7C12 7.55228 12.4477 8 13 8H18C18.5523 8 19 7.55228 19 7V2C19 1.44772 18.5523 1 18 1Z"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M18 12H13C12.4477 12 12 12.4477 12 13V18C12 18.5523 12.4477 19 13 19H18C18.5523 19 19 18.5523 19 18V13C19 12.4477 18.5523 12 18 12Z"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M7 12H2C1.44772 12 1 12.4477 1 13V18C1 18.5523 1.44772 19 2 19H7C7.55228 19 8 18.5523 8 18V13C8 12.4477 7.55228 12 7 12Z"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);

// List Icon Component (horizontal lines)
const ListIcon = ({ className }: { className?: string }) => (
  <svg
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    className={className}
  >
    <path
      d="M14 4H21M14 9H21M14 15H21M14 20H21M4 3H9C9.55228 3 10 3.44772 10 4V9C10 9.55228 9.55228 10 9 10H4C3.44772 10 3 9.55228 3 9V4C3 3.44772 3.44772 3 4 3ZM4 14H9C9.55228 14 10 14.4477 10 15V20C10 20.5523 9.55228 21 9 21H4C3.44772 21 3 20.5523 3 20V15C3 14.4477 3.44772 14 4 14Z"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);

const CardViewSwitcherComponent = ({
  onToggle,
  defaultCardView,
  onChange,
  value,
}: CardViewSwitcherProps) => {
  // Support both prop styles
  const handleChange = onChange || onToggle;
  const currentValue = value || defaultCardView || 'grid';

  return (
    <CardViewSwitcher.Root
      onValueChange={(val) => handleChange?.(val as 'list' | 'grid')}
      defaultValue={currentValue}
      className="inline-flex gap-1"
    >
      <CardViewSwitcher.Item
        value="grid"
        aria-label="Grid View"
        className="items-center rounded-md bg-transparent text-[#71717a] flex h-[30px] justify-center w-[30px] ml-0 hover:bg-gray-100 dark:hover:bg-gray-700 data-[state=on]:text-[#0c4a6e] dark:data-[state=on]:text-[#0c4a6e] focus:outline-none transition-colors"
      >
        <GridIcon className="h-5 w-5" />
      </CardViewSwitcher.Item>
      <CardViewSwitcher.Item
        value="list"
        aria-label="List View"
        className="items-center rounded-md bg-transparent text-[#71717a] flex h-[30px] justify-center w-[30px] ml-0 hover:bg-gray-100 dark:hover:bg-gray-700 data-[state=on]:text-[#0c4a6e] dark:data-[state=on]:text-[#0c4a6e] focus:outline-none transition-colors"
      >
        <ListIcon className="h-5 w-5" />
      </CardViewSwitcher.Item>
    </CardViewSwitcher.Root>
  );
};

export default CardViewSwitcherComponent;
export { CardViewSwitcherComponent as CardViewSwitcher };
